version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2
        environment:
          RAILS_ENV: develop
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
          PGUSER: anton.sikorski
      - image: circleci/postgres:12.9
        environment:
          POSTGRES_DB: trade_platform_development
          POSTGRES_USER: anton.sikorski
          POSTGRES_PASSWORD: 12345678
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler
      - restore_cache:
          name: Restore bundle cache
          key: trade_platform-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          name: Store bundle cache
          key: trade_platform-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rubocop
      - run: bundle exec rake db:setup
      - run: bundle exec rake