default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trade_platform_development

test:
  <<: *default
  database: trade_platform_test

production:
  <<: *default
  database: trade_platform_production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['TRADE_PLATFORM_DATABASE_PASSWORD'] %>
