default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432

development:
  <<: *default
  database: trade_platform_development

test:
  <<: *default
  database: trade_platform_test

production:
  <<: *default
  database: trade_platform_production
